# Generated by Django 3.2.6 on 2021-08-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
