# Generated by Django 3.2.6 on 2021-08-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img',
        ),
    ]
