# Generated by Django 3.2.6 on 2021-08-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_movie_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='Play',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='Tamaño',
        ),
    ]
